/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMunicipioArgs } from "./CreateMunicipioArgs";
import { UpdateMunicipioArgs } from "./UpdateMunicipioArgs";
import { DeleteMunicipioArgs } from "./DeleteMunicipioArgs";
import { MunicipioFindManyArgs } from "./MunicipioFindManyArgs";
import { MunicipioFindUniqueArgs } from "./MunicipioFindUniqueArgs";
import { Municipio } from "./Municipio";
import { Provincia } from "../../provincia/base/Provincia";
import { MunicipioService } from "../municipio.service";

@graphql.Resolver(() => Municipio)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MunicipioResolverBase {
  constructor(
    protected readonly service: MunicipioService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Municipio",
    action: "read",
    possession: "any",
  })
  async _municipiosMeta(
    @graphql.Args() args: MunicipioFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Municipio])
  @nestAccessControl.UseRoles({
    resource: "Municipio",
    action: "read",
    possession: "any",
  })
  async municipios(
    @graphql.Args() args: MunicipioFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Municipio[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Municipio",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Municipio, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Municipio",
    action: "read",
    possession: "own",
  })
  async municipio(
    @graphql.Args() args: MunicipioFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Municipio | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Municipio",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Municipio)
  @nestAccessControl.UseRoles({
    resource: "Municipio",
    action: "create",
    possession: "any",
  })
  async createMunicipio(
    @graphql.Args() args: CreateMunicipioArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Municipio> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Municipio",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Municipio"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        idProvincia: {
          connect: args.data.idProvincia,
        },
      },
    });
  }

  @graphql.Mutation(() => Municipio)
  @nestAccessControl.UseRoles({
    resource: "Municipio",
    action: "update",
    possession: "any",
  })
  async updateMunicipio(
    @graphql.Args() args: UpdateMunicipioArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Municipio | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Municipio",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Municipio"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          idProvincia: {
            connect: args.data.idProvincia,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Municipio)
  @nestAccessControl.UseRoles({
    resource: "Municipio",
    action: "delete",
    possession: "any",
  })
  async deleteMunicipio(
    @graphql.Args() args: DeleteMunicipioArgs
  ): Promise<Municipio | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Provincia, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Municipio",
    action: "read",
    possession: "any",
  })
  async idProvincia(
    @graphql.Parent() parent: Municipio,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Provincia | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Provincia",
    });
    const result = await this.service.getIdProvincia(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
