/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateProvinciaArgs } from "./CreateProvinciaArgs";
import { UpdateProvinciaArgs } from "./UpdateProvinciaArgs";
import { DeleteProvinciaArgs } from "./DeleteProvinciaArgs";
import { ProvinciaFindManyArgs } from "./ProvinciaFindManyArgs";
import { ProvinciaFindUniqueArgs } from "./ProvinciaFindUniqueArgs";
import { Provincia } from "./Provincia";
import { MunicipioFindManyArgs } from "../../municipio/base/MunicipioFindManyArgs";
import { Municipio } from "../../municipio/base/Municipio";
import { ProvinciaService } from "../provincia.service";

@graphql.Resolver(() => Provincia)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ProvinciaResolverBase {
  constructor(
    protected readonly service: ProvinciaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Provincia",
    action: "read",
    possession: "any",
  })
  async _provinciasMeta(
    @graphql.Args() args: ProvinciaFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Provincia])
  @nestAccessControl.UseRoles({
    resource: "Provincia",
    action: "read",
    possession: "any",
  })
  async provincias(
    @graphql.Args() args: ProvinciaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Provincia[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Provincia",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Provincia, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Provincia",
    action: "read",
    possession: "own",
  })
  async provincia(
    @graphql.Args() args: ProvinciaFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Provincia | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Provincia",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Provincia)
  @nestAccessControl.UseRoles({
    resource: "Provincia",
    action: "create",
    possession: "any",
  })
  async createProvincia(
    @graphql.Args() args: CreateProvinciaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Provincia> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Provincia",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Provincia"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Provincia)
  @nestAccessControl.UseRoles({
    resource: "Provincia",
    action: "update",
    possession: "any",
  })
  async updateProvincia(
    @graphql.Args() args: UpdateProvinciaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Provincia | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Provincia",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Provincia"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Provincia)
  @nestAccessControl.UseRoles({
    resource: "Provincia",
    action: "delete",
    possession: "any",
  })
  async deleteProvincia(
    @graphql.Args() args: DeleteProvinciaArgs
  ): Promise<Provincia | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Municipio])
  @nestAccessControl.UseRoles({
    resource: "Provincia",
    action: "read",
    possession: "any",
  })
  async municipios(
    @graphql.Parent() parent: Provincia,
    @graphql.Args() args: MunicipioFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Municipio[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Municipio",
    });
    const results = await this.service.findMunicipios(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
